dist: focal
os: linux
arch: arm64 # so we can use auto-spinup containers
language: node_js
node_js:
- '12'
cache: yarn
before_install:
- sudo apt-get update -qq
- sudo apt-get install libclang1-7 -y
- sudo ln -s /usr/lib/aarch64-linux-gnu/libclang-7.so.1 /usr/lib/aarch64-linux-gnu/libclang.so
install:
- bash .travis/setup-builder
script:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash .travis/run-pr; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash .travis/run-deploy; fi
notifications:
  email: false

addons:
  ssh_known_hosts: native-deploy-host.live.fivem.net

before_deploy:
  - openssl aes-256-cbc -K $encrypted_2b6ad88e47ae_key -iv $encrypted_2b6ad88e47ae_iv -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  edge: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/out/ travis@native-deploy-host.live.fivem.net:/home/travis/natives/
  on:
    branch: master